/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "picomsDataTypes_KR23.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(KR23_ThrusterCommand, KR23_ThrusterCommand, AUTO)


PB_BIND(KR23_AttachmentCommand, KR23_AttachmentCommand, AUTO)


PB_BIND(KR23_SensorsData, KR23_SensorsData, AUTO)


PB_BIND(KR23_SafetyData, KR23_SafetyData, AUTO)


PB_BIND(KR23_PollMessage, KR23_PollMessage, AUTO)


PB_BIND(KR23_OutgoingMessage, KR23_OutgoingMessage, AUTO)


PB_BIND(KR23_IncomingMessage, KR23_IncomingMessage, 2)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

